version: "3.8"
services:
  bridge-contracts:
    build: .
    command: "true"
    env_file: ./deploy/.env
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "true"
    env_file: ./deploy/.env
  foundry:
    build:
      context: .
      dockerfile: Dockerfile.foundry
    command: "true"
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
     - 8545:8545
